name: Build and Deploy
on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo npm install -g --unsafe-perm=true --allow-root
      - name: Install yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: yarn
      - run: yarn build
      - run: yarn export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
